services:
  laminas-mvc:
    image: php:8.2-fpm-alpine
    working_dir: "/app/laminas-mvc"
    volumes:
      - ".:/app"

  mezzio:
    image: php:8.2-fpm-alpine
    working_dir: "/app/mezzio"
    volumes:
      - ".:/app"

  symfony:
    image: php:8.2-fpm-alpine
    working_dir: "/app/mezzio"
    volumes:
      - ".:/app"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app:ro
    depends_on:
      - api
