api-ping:
    path: /api/ping
    controller: \App\ExternalApi\Controller\ApiController
home:
    path: /
    controller: \App\ExternalApi\Controller\HomeController::index
greetings:
    path: /api/greetings
    controller: \App\ExternalApi\Controller\UserGreetingsController::greetUser
    methods: [ "post" ]